version: '3.8'

services:
  api:
    build: .
    container_name: fiber-api
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASS=password
      - DB_NAME=fiber_db
      - DB_PORT=5432
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: fiber-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fiber_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
